# Generated by Django 5.0.6 on 2024-05-26 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '000X_populate_roles'),
    ]

    operations = [
    ]
